name: modis_summary
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3
    - click
    - fiona
    - numpy
    - pip
    - rasterio
    - shapely
    - pip:
        - https://github.com/roscavm/modis-summary/archive/master.zip